### ISSUE TITLE
[Windows] Cannot find flutter directory

### ISSUE THREAD

**Issue by skygate2012** [flutter-rs/flutter-rs#97]
```
PS C:\Users\0\Downloads\flutter-rs-master> psi run
Traceback (most recent call last):
  File "c:\users\0\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\0\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\0\AppData\Local\Programs\Python\Python37-32\Scripts\psi.exe\__main__.py", line 9, in <module>
  File "c:\users\0\appdata\local\programs\python\python37-32\lib\site-packages\psi\psi.py", line 29, in main
    args.func(args)
  File "c:\users\0\appdata\local\programs\python\python37-32\lib\site-packages\psi\subcmds\run.py", line 88, in run
    proj_dir = flutter_proj_dir()
  File "c:\users\0\appdata\local\programs\python\python37-32\lib\site-packages\psi\utils\__init__.py", line 37, in flutter_proj_dir
    raise Exception('Cannot find flutter directory')
Exception: Cannot find flutter directory
```
Environment variables were already set
![SystemPropertiesAdvanced](https://user-images.githubusercontent.com/7148976/71789444-11b39280-3066-11ea-81db-dddaf5f018c3.png)

**Comment by dvc94ch** [comment]
flutter-rs doesn't currently work on windows, and the `psi-cli` tools have been deprecated in favor of `cargo-flutter`. If you would like to help out on windows and speed up the process, you can find me on our Gitter channel

**Comment by dvc94ch** [comment]
Closing in favor of #106 and #100
